##### 2. [11 pts] Bob owns a root beer manufacturing plant in a far-off land where the basic monetary unit is the Herald.  As the CEO, Bob would like to make some long-range projections for his business.  After some forethought about how the business works, Bob asks you to do some calculations to see if anything worthwhile can be gleaned about the future.  Bob observes the following:
* Every quarter, the business spends 90% of what it collects in profits in the previous quarter.
* 2 thousand Heralds plus 8% of the company’s net worth last quarter gets invested each quarter.
*	Each quarter’s net worth is 300,000 Heralds plus 185% of the sum of that quarter’s business spending and that quarter’s investments.
*	Each quarter’s profits are 20% of that quarter’s net worth.
*	Revenue each quarter is 54,000 Heralds plus 70% of the difference between that quarter’s net worth and that quarter’s profits.

a)	Write five difference equations to represent this business model. [5 pts]\
b)	Express these difference equations in the form $\vec{x}_{n+1} = T \vec{x}_n + \vec{b}$  where the elements of $\vec{x}_n$  are the business spending, investment, net worth, profits, and revenue in period $n$, $\vec{b}$ are the constants in the difference equations, and $T$ is the coefficient matrix for the difference equations. [2 pts]\
c)	What is the equilibrium for business spending, investment, net worth, profits, and revenue? [2 pts] \
d)	How would you determine if this equilibrium is stable? [2 pts]


a) Difference Equations
  $$
  \begin{align}
  Spend_{n+1} &= 0.9P_n \\
  Invest_{n+1} &= 0.08Net_n + 2000 \\
  Net_{n+1} &= 0.148Net_n + 1.665P_n + 303700 \\
  P{n+1} & = 0.0296Net_n + 0.333P_n + 60740 \text{  (This is just 20% of the above) } \\ 
  Rev_{n+1} &= 0.08288Net_n + 0.9324P_n + 224072 \\
  \end{align}
  $$

b) 
$$
\begin{bmatrix}
  Spend_{n+1} \\
  Invest_{n+1}\\
  Net_{n+1} \\ 
  P{n+1} \\ 
  Rev_{n+1} \\
\end{bmatrix}
=
\begin{bmatrix}
0 & 0 & 0 & 0.9 & 0 \\ 
0 & 0 & 0.08 & 0 & 0 \\ 
0 & 0 & 0.148 & 1.665 & 0 \\ 
0 & 0 & 0.296 & 0.333 & 0 \\ 
0 & 0 & 0.8288 & 0.9324 & 0 \\
\end{bmatrix}
\vec x_{n} + 
\begin{bmatrix}
  0 \\
  2000 \\ 
  303700 \\
  60740 \\ 
  224072 \\ 
\end{bmatrix}
$$


d) We could tell if the equilibrium's are stable if we picked an arbitrary point close to the equilibruim. If the after multiple iterations we found that we were moving closer to equilibrium, then we the equlibrium would be considered stable. Specificaly though, since we are working in the multivariate case, if the eigenvalues are less than or equal to 1 and at least one eigen value is strictly less than 1, then the equilibruim is stable.  

In [ ]:
#c) 

from numpy import linalg as la

coeff = [[0,0,0,0.9,0],
         [0,0,0.08,0,0],
         [0,0,0.148,1.665,0],
         [0,0,0.296,0.333,0],
         [0,0,0.8288,0.9324,0]]
la.eig(np.array(coeff))


(array([ 0.        ,  0.        ,  0.        ,  0.94859339, -0.46759339]),
 array([[ 1.        ,  0.        ,  0.        ,  0.25270433,  0.42959048],
        [ 0.        ,  1.        ,  0.        ,  0.04671565, -0.10328147],
        [ 0.        ,  0.        ,  0.        ,  0.55392696,  0.60367166],
        [ 0.        ,  0.        ,  0.        ,  0.26634851, -0.22319296],
        [ 0.        ,  0.        ,  1.        ,  0.74577582, -0.6249403 ]]))

##### 3.	[4 pts] Consider the Root Beer Game:
a)	What was one thing about the game that was not “real”?  [1 pt]\
b)	As a decision maker in the game, what did you learn? [1 pt]\
c)	List two ways you would redesign this supply chain to better fill customer demands and reduce costs? [2 pts]

a) One thing that was not real was the consistency of the demand. In the real world, customer demand is usually much more erratic and much less pradictable 

b) I learned that having to do quick math to make orders based on the demand given while trying to calculate what orders I placed two turns ago leads to many errors. 

c.1) I would allow each person (factory, distributor) to communicate because once we *all* know that the demand is constant, we can do a just in time order policy. 

c.2) I would reduce the lag time to 0 therefore making orders and deliverys much easier to calculate. 

##### 4. [8 pts] Now consider the factory simulation developed in class.
a)	Derive an equation that can be used to determine the quantity to order each period.  This should be a function of inventory/backorders, orders, and/or demands up to that point in time.  Clearly explain this formula and why you think it is preferred to simply ordering what was just demanded. [5 pts]

This if statment checks to see if there are backorders. If there are backorders, we want our orders to increase based on what we just got delivered and our demand. We want more orders to make up for the back orders \\

$\text{ If Previous Inventory}  < 0:$ \\
 $order =  demand +0.1 \cdot delivery $ \\
This if statment checks if we have positive inventory. If we do then we want to minimize the amount of inventory to reduce cost, therefore we reduce the amount we order by subtracting a portion of our previous inventory from the demand. \\
$\text{ If Previous Inventory}  >= 0:$ \\
      $order = demand - .16 \cdot resource$ \\

4 b)	Implement the formula in the Python factory model and calculate the costs for each of the five demands provided and the sum of the costs. You will likely need to add code to make the calculation including adding a global variable or pass a variable. Please mark the code you add or change with a comment. [3 pt]

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/ialara/or-student/main/Data/Demands.csv'
demands = pd.read_csv(url, index_col=0)
demands

Day 1  Day 2  Day 3  Day 4  Day 5  Day 6  Day 7  Day 8  Day 9  \
Demands                                                                  
1            4      4      4      4      4      4      4      8      8   
2            4      4      4      4      4      4      4      2      2   
3            4      4      4      4      4      4      4      5      5   
4            4      4      4      4      4      4      4      8      8   
5            4      4      4      4      4      4      4      5      6   

         Day 10  ...  Day 26  Day 27  Day 28  Day 29  Day 30  Day 31  Day 32  \
Demands          ...                                                           
1             8  ...       8       8       8       8       8       8       8   
2             2  ...       2       2       2       2       2       2       2   
3             5  ...       9       9      10      10      10      10      11   
4             8  ...       4       4       3       3       3       3       2   
5             7  ...       8       7       6       5       4       3       2   

         Day 33  Day 34  Day 35  
Demands                          
1             8       8       8  
2             2       2       2  
3            11      11      11  
4             2       2       2  
5             2       3       4  

[5 rows x 35 columns]

In [ ]:
#Define variables
resources = np.zeros(35)
shipments = np.zeros(35)
orders = np.zeros(35)
costs = np.zeros(5)

def init():
  global resources
  global shipments
  global orders
  resources[:5] = 12
  shipments[:5] = 4
  orders[:5] = 4

def One_Week(last_resource, delivery, demand):
  resource = last_resource + delivery - demand
  if last_resource >= 0:
    shipment = min(last_resource + delivery, demand)
  else:
    shipment = min(delivery, -last_resource + demand)

  #****Your formula goes here*****
  if last_resource < 0: 
      order =  demand +0.1*delivery #This is implementing the above formula which gives a cost of ~465 for the factory
  if last_resource >= 0: 
      order = demand - .16*resource 
  

  return resource, shipment, order

def All_Weeks(demand_index, resources):
  for week in range(5, 35):
    resources[week], shipments[week], orders[week] = One_Week(resources[week-1], \
        orders[week-2], demands.iloc[demand_index][week])
  return resources

init()
for demand_index in range(5):  
  resources = All_Weeks(demand_index, resources)
  costs[demand_index] = 0.5*np.sum(resources*(resources>0)) - np.sum(resources*(resources<0))
    #Array of zeros and 1's is the 

print(costs, np.sum(costs))

[ 53.04310108  79.92146818  67.75226559  82.0337022  122.96127749] 405.71181453779957


##### 5.	[16 pts] We will now expand the Factory simulation to simulate the entire four-player supply chain.  We will do this in steps.
a)	The numpy arrays resources, shipments, and orders need to be changed to two-dimensional arrays with the first dimension the player (0 for the factory, 1 for the distributor, 2 for the wholesaler and 3 for the retailer) and the second dimension for the week. The init function must also be appropriately changed to include the starting conditions for all four players. Perform these changes. [6 pts]

(Note: I have also added the numpy array "customer" for the customer satifaction metric.)

In [ ]:
resources = np.zeros((4,36)) #Creating an array where each row is a player and each column is a week 
shipments = np.zeros((4,36))
orders = np.zeros((4,36))
customer = np.zeros(5)

def init():
  global resources #Defining the variables as globals to keep consistent throughout the code 
  global shipments
  global orders
  resources[:,:5] = 12 #Setting the first 5 weeks for all players to have resources of 12 
  shipments[:,:5] = 4 #Setting the first 5 weeks for all players to have shipments of 4
  orders[:,:5] = 4 #Setting the first 5 weeks for all players to have orders of 4


b)	We now add a function to cycle through each player in a given week.  To  simplify passing the resources, shipments, and orders arrays, we make them globals. Your job is to define delivery and demands for each of the players in terms of the arrays shipments, orders, and customer demand. [4 pts]

In [ ]:
def All_Players(demand_index, week):
  global resources
  global shipments
  global orders
  for player in range(4):
        #Supply the logic for defining delivery and demand for each player
    #If the player is the factory, then the delivery is just the order it made two weeks prior 
    if player == 0:  
      delivery = orders[player][week-2]
    #If the player is not the facotry then the delivery is just the shipment the previous player made two weeks ago 
    else:  
      delivery = shipments[player-1][week-2]
    #If the player is the retailer, he gets his demand from the customer which is taken form the demands table 
    if player == 3: 
      demand = demands.iloc[demand_index][week]
    #If the player is anyone else, their demand is the order from the player ahead of them, two weeks prior 
    else:
      demand = orders[player+1][week-2]
    
         
        
        
    resources[player][week], shipments[player][week], orders[player][week] = \
           One_Week(resources[player][week-1], delivery, demand)

c)	Since resources are defined as a global in All_Players, it is unnecessary to include it as an argument or a return value for All_Weeks. I have made these changes to the prior version of the function.

We do need to record the customer satisfaction for each customer demand in the customer array. This will be equivalent to the cumulative customer backorders. Your job is to add the code to calculate the customer satisfaction for each of the demands.  Put your code in the line noted below. [2 pts]

In [ ]:
def All_Weeks(demand_index):
  for week in range(5,35):
    All_Players(demand_index, week)

init()
for demand_index in range(5):
  All_Weeks(demand_index)
  costs[demand_index] = 0.5*np.sum(resources*(resources>0)) - np.sum(resources*(resources<0))
  
  #Supply the equation for the customer satisfaction for demand  specified by demand_index.
  #Customer satesfaction is equal to the sum of the backorders (which are negative, therefore the more negative, the lower the satesfaction)
  customer[demand_index] = np.sum(resources*(resources<0)) 

print(costs, np.sum(costs))
print(customer, np.sum(customer))

[3005.88269318 2173.78868935 3378.31759539 1696.37904954 1807.15209939] 12061.520126854975
[-2719.37581318 -1675.08140569 -3045.65384371 -1337.54697231
 -1491.61360339] -10269.271638286491


d)	Change the order equation in the One_Week function back to "order = demand". Supply the results from the two print statements at the bottom of the code. [4 pts]

[ 808. 1177.  890.  645.  646.] 4166.0

[-504.    0. -488.  -42.  -24.] -1058.0